Update deps (v2)
digitalbazaar/bedrock-webpack pull request #41
Opened 2022-04-12 02:03 UTC by davidlehn

Newer version of https://github.com/digitalbazaar/bedrock-webpack/pull/37, rebased on main, more updates, and fixed issues.

Got to work with a top level module based app.  Seemed to work with dev and production.  Needs more testing.

- Some of the newer `[hash]` lines may need to be updated for v5.
- The data is all dumped into `js/`.  This can be adjusted to just use one main dir but it also needs a tweak in `@bedrock/views` for it to work. Could do both changes or just leave that until these two packages get merged.

2022-04-12 14:09 UTC, dlongley requested changes

2022-04-12 14:09 UTC, dlongley commented on lib/index.js
>                      debug: command.webpackBabelDebug === 'true'
I recommend we make it our default behavior not to support IE11 now. This removes the regenerate polyfill which can create massive bloat for very little to no gain in terms of user base.

```suggestion
                    debug: command.webpackBabelDebug === 'true',
                    targets: ['defaults', 'not IE 11'],
```

2022-04-12 14:12 UTC, gannan08 reviewed
[This](https://github.com/digitalbazaar/bedrock-webpack/pull/41/files#diff-92bbac9a308cd5fcf9db165841f2d90ce981baddcb2b1e26cfff170929af3bd1L312-L313
) could be changed to "/dist" in the future. I rather get this PR in now. It is unclear the impacts of changing the output path for our frontend builds.

2022-04-14 00:29 UTC, dlongley approved these changes

2022-04-14 00:30 UTC, merged